examples/default_array.rs
papergrid/src/lib.rs
src/alignment.rs
src/disable.rs
src/formating.rs
src/indent.rs
src/lib.rs
src/object.rs
src/panel.rs
src/style.rs
src/width.rs

I really, really appreciate this package. And I wanted to go through it and
use the new way to refer to types in rustdoc. A few things have come up, that
would be nice if we could go through:

Going through all the documentation and trying to use

---

README.md
examples/basic.rs
examples/color.rs
examples/default_array.rs
examples/format.rs
examples/inline.rs
examples/panel.rs
examples/rotate.rs
examples/width.rs
src/lib.rs
src/style.rs
src/width.rs
tests/alignment_test.rs
tests/disable_test.rs
tests/format_test.rs
tests/highlingt_test.rs
tests/indent_test.rs
tests/panel_test.rs
tests/rotate_test.rs
tests/style_test.rs
tests/table_test.rs
tests/width_test.rs

Removing deprecated functions will be a breaking change.
So probably then the library must bump version to `1.0.0`

tabled/ change style functions to constants

---

src/lib.rs
tests/table_test.rs

I watched the video in Issue #36 and it seems interesting. So I made `TableIteratorExt` trait to support `table()` function. 
(If the comment are needed let me add it. If the trait name is not good let me change it)
```rust
let people: Vec<Person> = ...
let table = people.table()
.with(Style::psql());
```
The `TableIteratorExt` applies to the type `U` which is bound to `IntoIterator<Item = T>` type. (T is bound to `Tabled` type)
I don't know which tests to be added, so I simply added one test to `table_test.rs`

Implement table() trait

---

examples/panel.rs
papergrid/src/lib.rs
papergrid/tests/render.rs
src/style.rs
tests/panel_test.rs

It changes and approach of rendering split lines for spanned cells.

papergrid/ Fix split line styling

---

.github/workflows/ci.yml

An additional step isn't needed. We can rely on `components`, a comma-separated list of the additional components to install.
Just something I've noticed when looking at the project.

Use components in actions-rs/toolchain@v1

---

src/table.rs

To have the same behaviour as `Table::new()` and avoid having headers mixed with the body of the table.
For example running `./table_to_html/examples/basic.rs` on master produces:
``` html
<table id="tabled-table" border="1">
<tbody>
<tr id="tabled-table-0">
<td id="tabled-table-0-0" style="padding-top: 0rem; padding-bottom: 0rem; padding-left: 1rem; padding-right: 1rem;" style="text-align: center;">
<p> name </p>
</td>
<td id="tabled-table-0-1" style="padding-top: 0rem; padding-bottom: 0rem; padding-left: 1rem; padding-right: 1rem;" style="text-align: center;">
<p> based_on </p>
</td>
<td id="tabled-table-0-2" style="padding-top: 0rem; padding-bottom: 0rem; padding-left: 1rem; padding-right: 1rem;" style="text-align: center;">
<p> is_active </p>
</td>
</tr>
<tr id="tabled-table-1">
<td …
```

table: set headers when building from a reference iterator

---

json_to_table/tests/test_config.rs

this test has the wrong type in the constructor
i guess the CI is not covering this feature?
looks like the `check` target is not checking `--all-targets` or the whole workspace (`--all`)

fix json_to_table test

---

.github/workflows/ci.yml

'actions-rs' is unmaintained. This PR removes *most* of the usages from CI

deprecates most usages of 'actions-rs'

---

tabled/src/records/vec_records.rs

This change will keep `records.count_rows()` up-to-date with the tables shape after row insertion.
This bug was impacting my work on a new Split setting. If I've missing something obvious please let me know 😄

update table shape with vec_records insert_row function

---

tabled/src/records/mod.rs
tabled/src/records/vec_records.rs

I have a draft of Split ready to put up, but I needed to add this function to achieve all of the options discussed in https://github.com/zhiburt/tabled/issues/290. I figured it would be safer to split this dependent work into it's own PR so we can workshop any necessary changes you'd like to see before this goes in.
|          | Append | Zip    |
|:--------:|:------:|:------:|
| column(usize)   |   ✅    |   ✅    |
| row(usize)      |   ✅    | Requires changes in this PR |
---
P.S. I'm getting a yellow squiggly that says 
>missing documentation for an associated function
I'm not sure if that's referring to generated documentation online? I've added a doc comment above the function like insert_row().
https://github.com/zhiburt/tabled/blob/2319a19b0c80aa504476d68f2146211326bf43ed/tabled/src/r …

add new function `insert_column` to Resizable trait

---

README.md

Added another example, a link and hopefully larger surface area for people searching for a solution for working with colors inside a table. Took me quite a while to find that feature as i've searched for:
* broken ansi
* color in cell
* bad layout
and other search terms, just to hit issue #26 which deals with _hyperlinks_ ansi, but describes the problem well.
After I've used the color feature, everything works like magic!

Better discoverability for `color` feature in README.md

---

tabled/tests/derive_test.rs
tabled_derive/src/lib.rs

and the caller doesn't need to import Tabled trait

fix(macro hygiene): use the absolute path in Tabled derive macro

---

tabled/src/lib.rs

I'm using tabled on my project, and if I find any other typos, I'd be happy to fix them in the same pull request if it's not yet merged.
In the meantime, if someone has found another typo(or documentation fix) then this PR can be used for the same.
Thank you

Typo: on lib.rs docs comment from "almoust" to "almost"

---

tabled/src/builder/index_builder.rs
tabled/tests/core/index_test.rs

There's a minor behaviour difference between how `Builder` and `IndexBuilder` handles tables that have no data rows but a header row. In that case, `Builder` will regard the header row itself as data, but `IndexBuilder` will not. This difference shows up when `table.is_empty()` is called on the resulting tables: such tables will have different shapes.
This patch fixes the process when an `IndexBuilder` is converted back to a `Builder`. With this patch, a default `Builder` will be returned only if the `IndexBuilder` has neither data rows nor a header row.
Unit tests are added accordingly.
Fix #363 
Now this code works:
```rust
use tabled::builder::Builder;
fn main() -> Result<()> {
let mut builder = Builder::default();
builder.set_header(["color", "vegetable", "contains"]);
let builder = …
```

tabled/ Fix IndexBuilder on empty tables (#363)

---

tabled/src/tables/table.rs

Noticed this while browsing the docs.
Thanks for this awesome library!

Fix typo in `Table::modify` doc comment.

---

json_to_table/src/table/collapsed_table.rs
papergrid/src/records/vec_records/mod.rs
table_to_html/tests/html.rs
tabled/Cargo.toml
tabled/src/grid/records/resizable.rs
tabled/src/tables/table_pool.rs
tabled/tests/derive/derive_test.rs
tabled_derive/src/lib.rs

Seems to work @elenakrittik?
https://github.com/zhiburt/tabled/blob/7ec7973c1814be4cd909b399357c36d45464c1a7/tabled/tests/derive/derive_test.rs#L1084-L1091
close #395

tabled_derive/ Fix issue with Cow usage

---

README.md
tabled/tests/derive/derive_test.rs
tabled_derive/src/attributes.rs
tabled_derive/src/lib.rs
tabled_derive/src/parse.rs

Hello,
This is for #396 .
I hope it's fine, it was probably a bit too difficult for me as a first issue. I tried to do something very similar to display_with but I encounter some difficulties with properties and nested structs/enums. I would be happy to see what corrections you can make to improve it.
By the way, thanks a lot for the library! :)
FYI, I needed that for this project : https://github.com/thomassimmer/NeoPass
Cheers

Tabled attribute format

---

json_to_table/src/table/collapsed_table.rs
papergrid/src/config/spanned/mod.rs
tabled/src/settings/merge/mod.rs
tabled/src/settings/width/truncate.rs
tabled/src/tables/table_pool.rs

This PR fixes the issue of clippy failing in CI.
As noted in the comments, I've temporarily disabled `assiginig_clones` due to a bug in which clippy does not respect the version of rust. (`assiginig_clones` is actually available since rust 1.63.0. Currently the [`rust-version` in `Cargo.toml` is 1.61.0](https://github.com/zhiburt/tabled/blob/f454b5ab6efd2f2a6b3c3a416098d4fd1347315d/tabled/Cargo.toml#L14).)
ref: https://github.com/rust-lang/rust-clippy/issues/12502

Fix for cargo clippy

---

papergrid/src/config/position.rs
tabled/src/settings/object/cell.rs

also update `papergrid` `Position` `derive`

add `Clone`, `Copy` to `tabled::settings::object::Cell`

---

papergrid/src/config/position.rs

https://github.com/zhiburt/tabled/pull/406#issuecomment-2176038543

fix: do not apply `derive` on `type Position`

---

README.md

This fixes a few spelling and grammar issues I noticed in the README.
Overall I tried not to change the structure too much, but rather made
small tweaks to make it sound a little more correct.
This also removes trailing whitespace from some lines.

Fix some typos and grammar issues in the README.

---

static_table/src/static_table.rs

https://rust-lang.github.io/rust-clippy/master/index.html#single_match
```
error: you seem to be trying to use `match` for destructuring a single pattern. Consider using `if let`
--> static_table/src/static_table.rs:400:60
|
400 |   ...                   ExprVal::Scope { expr, .. } => match expr {
|  ______________________________________________________^
401 | | ...                       Some(val) => match val {
402 | | ...                           ScopeVal::Expr(_) => {}
403 | | ...                           ScopeVal::List(_) => {}
...   |
412 | | ...                       None => {}
413 | | ...                   },
| |_______________________^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_match
= note: `-D clippy::single-match` …
```

Fix single_match warning

---

json_to_table/README.md

`set_object_mode` method has been renamed to `object_orientation` at #321.
https://github.com/zhiburt/tabled/blob/300c07bd53c945671e8115811c1689cb1353feff/json_to_table/src/table/mod.rs#L186-L189

Fix README.md for json_to_table

---

static_table/Cargo.toml
static_table/src/lib.rs
static_table/src/pool_table.rs
static_table/src/static_table.rs
tabled_derive/Cargo.toml
tabled_derive/src/error.rs
tabled_derive/src/lib.rs

Replaces the `proc-macro-error` crate with [`proc-macro-error2`](https://github.com/GnomedDev/proc-macro-error-2), an actively maintained fork.
Resolves #425.
- Replace `proc-macro-error` with the latest version of `proc-macro-error2` in `Cargo.toml`
- Replace `proc-macro-error` references with `proc-macro-error2`
The `proc-macro-error` crate has been flagged as unmaintained ([RUSTSEC-2024-0370](https://rustsec.org/advisories/RUSTSEC-2024-0370)). Migrating to `proc-macro-error2` addresses this security advisory and ensures our project uses an actively maintained dependency.

fix(deps): migrate from proc-macro-error to proc-macro-error2

---

CHANGELOG.md
static_table/Cargo.toml
static_table/src/pool_table.rs
static_table/src/static_table.rs
tabled_derive/Cargo.toml
tabled_derive/src/lib.rs
tabled_derive/src/parse/field_attr.rs
tabled_derive/src/parse/type_attr.rs

Updates to syn 2.0
Note that the `expr_lit_to_string` function now returns an error. A CString cannot be turned into a String, without possible error. I'm not sure how you wanted this to be handled. Also, it is nonexhaustive now. 
Also closes #313

Update to syn 2

---

tabled/src/tables/table.rs
tabled/tests/core/kv_test.rs
tabled/tests/core/mod.rs

Add `Tabled::kv` method to construct KV layout

---

tabled/Cargo.toml
tabled/examples/derive/display_with_option.rs
tabled_derive/src/attributes/type_attr.rs
tabled_derive/src/lib.rs
tabled_derive/src/parse/type_attr.rs

I have some structs with a bunch of `Option` fields i want to put in the table
i found https://github.com/zhiburt/tabled/issues/265 but it is not ergonomic to put attr on each field, so add type-level attr

feat: adds display_option_with type attr

---

README.md

Just found this great library and noticed some broken links in the readme, hopefully I pointed them to the correct new link

Fix docs.rs links in README

---

ron_to_table/Cargo.toml
ron_to_table/src/table.rs
ron_to_table/tests/collapse_tests.rs
ron_to_table/tests/plain_tests.rs

Update ron to 0.9

---

tabled/Cargo.toml

Currently `tabled` pulls `testing_table` dep for `std` and `ansi` features unconditionally. Fixes this, so features for `testing_table` will be used only if `testing_table` enabled.
Spotted when updated to tabled 0.19.

tabled: don't pull testing_table until assert feature selected
